name: workout_routines_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.1.1
  flutter_svg: ^2.0.10+1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - lib/api/exercise.json

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
